[settings]

### adiff.py settings
IDIFF2_PATH = ~/decant/lib/python3.13/site-packages/dfxml/bin/idifference2.py
SECTOR_SIZE = 512 # 512, 4096, etc. - use image drive sector size
IMAGE_LIST = 0.001, 1.001, 2.001 # order matters; deleted files are found from first to second image in this list
HAVE_TEMP_DFXML = False # True if temp.dfxml already exists, saves time

### trace_file.py settings
# Database settings
DB = deleted.db          # main database file
DBT = deleted_files      # table name
# Output flags
CREATE_GRAPHS = True         ; plot line graphs to PDF
WRITE_FILE = True            ; write graph data to graphdata.out
PLOT_ALL_ON_ONE = True       ; all lines on one graph vs separate
OUTPUT_CHANGES_BY_IMAGE = False   ; show sector-by-sector decay
OUTPUT_FINAL_PERSISTENCE = True  ; show final % persistence
CREATE_PROCESSED_CSV = True      ; write processed data to CSV
